# Generated by Django 5.1.2 on 2024-11-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
